const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONTACTING: 'CONTACTING',
  VERIFYING: 'VERIFYING',
  VERIFIED: 'VERIFIED',
  INVALID_INFO: 'INVALID_INFO',
  CORRECTING: 'CORRECTING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  DISPATCHING: 'DISPATCHING',
  ASSIGNED: 'ASSIGNED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  DEMAND_SUBMITTED: 'DEMAND_SUBMITTED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  PRE_SCREEN_REJECTED: 'PRE_SCREEN_REJECTED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REVIEW_REJECTED: 'REVIEW_REJECTED',
  PENDING_CONTACT: 'PENDING_CONTACT',
  CONTACT_FAILED: 'CONTACT_FAILED',
  CLIENT_DECLINED: 'CLIENT_DECLINED',
  PENDING_SERVICE_MODE: 'PENDING_SERVICE_MODE',
  PENDING_APPOINTMENT: 'PENDING_APPOINTMENT',
  PENDING_DISPATCH: 'PENDING_DISPATCH',
  PENDING_SERVICE: 'PENDING_SERVICE',
  IN_SERVICE: 'IN_SERVICE',
  PENDING_STORE_SERVICE: 'PENDING_STORE_SERVICE',
  IN_STORE_SERVICE: 'IN_STORE_SERVICE',
  SERVICE_FAILED: 'SERVICE_FAILED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFICATION_RETURNED: 'VERIFICATION_RETURNED',
  SERVICE_COMPLETED: 'SERVICE_COMPLETED',
  WITHDRAWN: 'WITHDRAWN',
  CLOSED: 'CLOSED'
})

module.exports = {
  ORDER_STATUS
}
