const TASK_STATUS = Object.freeze({
  PENDING_ACCEPT: 'PENDING_ACCEPT',
  ACCEPTED: 'ACCEPTED',
  WAITING_CONTACT: 'WAITING_CONTACT',
  CONTACT_FAILED: 'CONTACT_FAILED',
  CONTACTED: 'CONTACTED',
  WAITING_TIME_CONFIRMATION: 'WAITING_TIME_CONFIRMATION',
  TIME_CONFIRMED: 'TIME_CONFIRMED',
  WAITING_HOME_SERVICE: 'WAITING_HOME_SERVICE',
  WAITING_CUSTOMER_ARRIVAL: 'WAITING_CUSTOMER_ARRIVAL',
  WAITING_START_CONFIRMATION: 'WAITING_START_CONFIRMATION',
  PROCESSING: 'PROCESSING',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  WAITING_RESULT_UPLOAD: 'WAITING_RESULT_UPLOAD',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  ABNORMAL_CLOSED: 'ABNORMAL_CLOSED'
})

const TASK_STATUS_TEXT = Object.freeze({
  PENDING_ACCEPT: '待接收', ACCEPTED: '已接收', WAITING_CONTACT: '待联系客户',
  CONTACT_FAILED: '联系失败，待重联', CONTACTED: '已联系客户',
  WAITING_TIME_CONFIRMATION: '待确认办理时间', TIME_CONFIRMED: '办理时间已确认',
  WAITING_HOME_SERVICE: '等待上门', WAITING_CUSTOMER_ARRIVAL: '等待客户到店',
  WAITING_START_CONFIRMATION: '待确认开始办理', PROCESSING: '办理中',
  PROCESSING_FAILED: '办理失败', WAITING_RESULT_UPLOAD: '待上传办理结果',
  PENDING_VERIFICATION: '等待客服核销', COMPLETED: '已完成', CANCELLED: '已取消',
  ABNORMAL_CLOSED: '异常结束'
})

const TASK_TRANSITIONS = Object.freeze({
  PENDING_ACCEPT: ['ACCEPTED'],
  ACCEPTED: ['WAITING_CONTACT', 'ABNORMAL_CLOSED'],
  WAITING_CONTACT: ['CONTACTED', 'CONTACT_FAILED', 'ABNORMAL_CLOSED'],
  CONTACT_FAILED: ['CONTACTED', 'CONTACT_FAILED', 'ABNORMAL_CLOSED'],
  CONTACTED: ['WAITING_TIME_CONFIRMATION', 'ABNORMAL_CLOSED'],
  WAITING_TIME_CONFIRMATION: ['TIME_CONFIRMED', 'ABNORMAL_CLOSED'],
  TIME_CONFIRMED: ['WAITING_HOME_SERVICE', 'WAITING_CUSTOMER_ARRIVAL', 'ABNORMAL_CLOSED'],
  WAITING_HOME_SERVICE: ['WAITING_START_CONFIRMATION', 'ABNORMAL_CLOSED'],
  WAITING_CUSTOMER_ARRIVAL: ['WAITING_START_CONFIRMATION', 'ABNORMAL_CLOSED'],
  WAITING_START_CONFIRMATION: ['PROCESSING', 'ABNORMAL_CLOSED'],
  PROCESSING: ['WAITING_RESULT_UPLOAD', 'ABNORMAL_CLOSED'],
  WAITING_RESULT_UPLOAD: ['PENDING_VERIFICATION', 'ABNORMAL_CLOSED'],
  PENDING_VERIFICATION: ['COMPLETED', 'WAITING_RESULT_UPLOAD'],
  PROCESSING_FAILED: [], COMPLETED: [], CANCELLED: [], ABNORMAL_CLOSED: []
})

function canTransitionTask(from, to) { return (TASK_TRANSITIONS[from] || []).includes(to) }

module.exports = { TASK_STATUS, TASK_STATUS_TEXT, TASK_TRANSITIONS, canTransitionTask }
