const BILL_STATUS = Object.freeze({
  NOT_RECORDED: 'NOT_RECORDED',
  RECORDED: 'RECORDED',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  REFUND_POSTED: 'REFUND_POSTED',
  CORRECTED: 'CORRECTED',
  VOIDED: 'VOIDED'
})

module.exports = {
  BILL_STATUS
}
